# Generated by Django 4.1.5 on 2023-01-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('nome', models.CharField(help_text='Endereço único da página, criado por Hash MD5.', max_length=64, primary_key=True, serialize=False, verbose_name='Nome')),
                ('created', models.DateField(auto_now_add=True, help_text='Data de criação da página.')),
            ],
            options={
                'verbose_name': 'Paginas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('cadastro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saveurl.cadastro')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('enviar', models.BooleanField(default=False)),
            ],
            bases=('saveurl.cadastro',),
        ),
    ]
