# Generated by Django 4.1.5 on 2023-01-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('nome', models.CharField(help_text='Endereço único da página, criado por Hash MD5.', max_length=64, primary_key=True, serialize=False, verbose_name='link')),
                ('created', models.DateField(auto_now_add=True, help_text='Data de criação da página.')),
            ],
            options={
                'verbose_name': 'Cadastros',
                'ordering': ['-nome'],
            },
        ),
    ]
