# Generated by Django 4.1.5 on 2023-01-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Endereço único da página, criado por Hash MD5.', max_length=64, verbose_name='Nome')),
                ('created', models.DateField(auto_now_add=True, help_text='Data de criação da página.')),
            ],
            options={
                'verbose_name': 'Paginas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(help_text='URLs para armazenar.', max_length=400, verbose_name='urls')),
                ('created', models.DateField(auto_now_add=True, help_text='Data que o link foi inserido.')),
                ('updated', models.DateField(auto_now=True, help_text='Data da ultima atualização da página.')),
                ('cadastro_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saveurl.cadastro')),
            ],
            options={
                'verbose_name': 'Dados',
                'ordering': ['-updated'],
            },
        ),
    ]
