# Generated by Django 4.1.5 on 2023-01-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(help_text='Endereço único da página, criado por Hash MD5.', max_length=64, primary_key=True, serialize=False, verbose_name='nome'),
        ),
    ]
