# Generated by Django 4.1.5 on 2023-01-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0002_alter_cadastro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-created'], 'verbose_name': 'Paginas'},
        ),
    ]
