# Generated by Django 4.1.5 on 2023-01-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0002_alter_cadastro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='enviar',
            field=models.BooleanField(blank=True, help_text='Enviar link para seu email', null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(help_text='Endereço único da página, criado por Hash MD5.', max_length=64, primary_key=True, serialize=False, verbose_name='Nome'),
        ),
    ]
