# Generated by Django 4.1.5 on 2023-01-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0003_cadastro_email_cadastro_enviar_alter_cadastro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='enviar',
            field=models.BooleanField(blank=True, default=False, help_text='Enviar link para seu email', null=True),
        ),
    ]
