# Generated by Django 4.1.5 on 2023-01-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0004_alter_cadastro_enviar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='enviar',
            field=models.BooleanField(blank=True, null=True, verbose_name='Enviar link para seu email'),
        ),
    ]
