# Generated by Django 4.1.5 on 2023-01-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0005_alter_cadastro_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Data de criação da página.'),
        ),
    ]
