# Generated by Django 4.1.5 on 2023-01-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0005_alter_cadastro_enviar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='enviar',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
