# Generated by Django 4.1.5 on 2023-01-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0006_alter_cadastro_enviar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='enviar',
            field=models.BooleanField(default=False),
        ),
    ]
