# Generated by Django 4.1.5 on 2023-01-07 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0006_alter_cadastro_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.CharField(help_text='URLs armazenadas.', max_length=400, verbose_name='urls')),
                ('created', models.DateField(auto_now_add=True, help_text='Data que o link foi inserido.')),
                ('updated', models.DateField(auto_now=True, help_text='Data da ultima atualização da página.')),
                ('cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saveurl.cadastro')),
            ],
            options={
                'verbose_name': 'Dados',
                'ordering': ['-updated'],
            },
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
    ]
