# Generated by Django 4.1.5 on 2023-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0007_dados_delete_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='urls',
            field=models.URLField(help_text='URLs armazenadas.', max_length=400, verbose_name='urls'),
        ),
    ]
