# Generated by Django 4.1.5 on 2023-01-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveurl', '0008_alter_dados_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='urls',
            field=models.URLField(help_text='URLs para armazenar.', max_length=400, verbose_name='urls'),
        ),
    ]
